[package]
name = "rust_mcp_template"
version = "0.1.0"
edition = "2024"

[dependencies]
cmake = "0.1.54"
prism-mcp-rs = { version = "1.1.1", features = ["full"] }
tokio = { version = "1.48.0", features = ["full"] }
